window.chapterData = {
  title: "第1章 原子の構造と元素の周期表・化学結合・物質量と化学反応式",
  sections: [
    {
      subtitle: "原子の構造と元素の周期表",
      questions: [
        { label: "問1", name: "a1", answer: 7 },
        { label: "問2", name: "a2", answer: 4 },
        { label: "問3", name: "a3", answer: 4 },
        { label: "問4", name: "a4", answer: 6 },
        { label: "問5", name: "a5", answer: 4 },
        { label: "問6", name: "a6", answer: 3 },
        { label: "問7", name: "a7", answer: 5 },
        { label: "問8", name: "a8", answer: 4 },
        { label: "問9", name: "a9", answer: 2 },
        { label: "問10", name: "a10", answer: 1 },
        { label: "問11", name: "a11", answer: 1 },
        { label: "問12", name: "a12", answer: 5 },
        { label: "問13", name: "a13", answer: 2 },
        { label: "問14", name: "a14", answer: 6 },
        { label: "問15", name: "a15", answer: 4 },
        { label: "問16", name: "a16", answer: 4 },
        { label: "問17", name: "a17", answer: 2 },
        { label: "問18", name: "a18", answer: 3 },
        { label: "問19", name: "a19", answer: 5 },
        { label: "問20", name: "a20", answer: 3 },
        { label: "問21", name: "a21", answer: 2 },
        { label: "問22", name: "a22", answer: 4 },
        { label: "問23", name: "a23", answer: 4 },
        { label: "問24", name: "a24", answer: 1 },
        { label: "問25", name: "a25", answer: 2 }
      ]
    },
    {
      subtitle: "化学結合",
      questions: [
        { label: "問1", name: "b1", answer: 3 },
        { label: "問2", name: "b2", answer: 5 },
        { label: "問3", name: "b3", answer: 1 },
        { label: "問4", name: "b4", answer: 2 },
        { label: "問5", name: "b5", answer: 5 },
        { label: "問6", name: "b6", answer: 5 },
        { label: "問7", name: "b7", answer: 6 },
        { label: "問8", name: "b8", answer: 4 },
        { label: "問9", name: "b9", answer: 3 },
        { label: "問10", name: "b10", answer: 6 },
        { label: "問11", name: "b11", answer: 1 },
        { label: "問12", name: "b12", answer: 3 },
        { label: "問13", name: "b13", answer: 3 },
        { label: "問14", name: "b14", answer: 5 },
        { label: "問15", name: "b15", answer: 5 },
        { label: "問16", name: "b16", answer: 5 },
        { label: "問17", name: "b17", answer: 3 },
        { label: "問18", name: "b18", answer: 2 },
        { label: "問19", name: "b19", answer: 2 },
        { label: "問20", name: "b20", answer: 6 },
        { label: "問21", name: "b21", answer: 3 },
        { label: "問22", name: "b22", answer: 4 },
        { label: "問23", name: "b23", answer: 1 },
        { label: "問24", name: "b24", answer: 5 },
        { label: "問25", name: "b25", answer: 1 }
      ]
    },
    {
      subtitle: "物質量と化学反応式",
      questions: [
        { label: "問1", name: "c1", answer: 4 },
        { label: "問2", name: "c2", answer: 3 },
        { label: "問3", name: "c3", answer: 4 },
        { label: "問4", name: "c4", answer: 3 },
        { label: "問5", name: "c5", answer: 3 },
        { label: "問6", name: "c6", answer: 2 },
        { label: "問7", name: "c7", answer: 4 },
        { label: "問8", name: "c8", answer: 1 },
        { label: "問9", name: "c9", answer: 6 },
        { label: "問10", name: "c10", answer: 4 },
        { label: "問11", name: "c11", answer: 5 },
        { label: "問12", name: "c12", answer: 5 },
        { label: "問13", name: "c13", answer: 4 },
        { label: "問14", name: "c14", answer: 3 },
        { label: "問15", name: "c15", answer: 4 },
        { label: "問16", name: "c16", answer: 1 },
        { label: "問17", name: "c17", answer: 2 },
        { label: "問18", name: "c18", answer: 2 },
        { label: "問19", name: "c19", answer: 4 },
        { label: "問20", name: "c20", answer: 4 }
      ]
    }
  ]
};
